[package]
name = "event_router"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1"
inventory = "0.3"

